[2023-11-12 14:08:19,143: INFO: main: Welcome to our custom log.]
[2023-11-12 14:13:19,290: INFO: main: Welcome to our custom log.]
[2023-11-14 09:38:23,482: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 09:38:23,487: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 09:38:23,492: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 09:38:23,495: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/utils/common.py", line 33, in read_yaml
    return ConfigBox(content)
  File "box/box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    data_ingestion.main()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/pipeline/stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/config/configuration.py", line 17, in __init__
    self.params = read_yaml(params_filepath)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/ensure/main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/utils/common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2023-11-14 09:40:41,878: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 09:40:41,884: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 09:40:41,889: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 09:40:41,898: INFO: common: created directory at: artifacts]
[2023-11-14 09:40:41,905: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-14 09:40:41,907: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 09:41:06,953: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 09:42:25,656: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-14 11:55:22,779: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 11:55:22,803: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 11:55:22,809: INFO: common: created directory at: artifacts]
[2023-11-14 13:09:49,882: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 13:09:49,928: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 13:09:49,937: INFO: common: created directory at: artifacts]
[2023-11-14 13:15:26,048: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 13:15:26,055: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 13:15:26,061: INFO: common: created directory at: artifacts]
[2023-11-14 13:19:20,331: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 13:19:20,338: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 13:19:20,343: INFO: common: created directory at: artifacts]
[2023-11-14 13:19:43,217: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 13:19:43,223: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 13:19:43,230: INFO: common: created directory at: artifacts]
[2023-11-14 13:25:16,324: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 13:25:16,330: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 13:25:16,336: INFO: common: created directory at: artifacts]
[2023-11-14 13:27:59,183: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 13:27:59,189: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 13:27:59,196: INFO: common: created directory at: artifacts]
[2023-11-14 13:27:59,202: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-14 13:28:02,223: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-14 13:33:15,379: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 13:33:15,382: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 13:33:15,385: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 13:33:15,388: INFO: common: created directory at: artifacts]
[2023-11-14 13:33:15,392: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-14 13:33:15,396: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 13:33:41,826: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 13:35:58,108: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-14 13:35:58,109: INFO: main: *******************]
[2023-11-14 13:35:58,109: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-14 13:35:58,115: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 13:35:58,119: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 13:35:58,124: INFO: common: created directory at: artifacts]
[2023-11-14 13:35:58,133: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-14 13:35:58,550: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-14 13:35:59,317: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-14 13:57:22,366: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 13:57:22,375: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 13:57:22,381: INFO: common: created directory at: artifacts]
[2023-11-14 13:57:22,387: INFO: common: created directory at: artifacts/training]
[2023-11-14 14:21:05,831: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 14:21:05,838: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 14:21:05,846: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 14:21:05,852: INFO: common: created directory at: artifacts]
[2023-11-14 14:21:05,856: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-14 14:21:05,859: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 14:22:02,147: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 14:24:35,583: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-14 14:24:35,584: INFO: main: *******************]
[2023-11-14 14:24:35,584: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-14 14:24:35,587: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 14:24:35,592: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 14:24:35,596: INFO: common: created directory at: artifacts]
[2023-11-14 14:24:35,599: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-14 14:24:37,089: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-14 14:24:37,611: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-14 14:24:37,611: INFO: main: *******************]
[2023-11-14 14:24:37,612: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-11-14 14:24:37,619: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 14:24:37,633: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 14:24:37,637: INFO: common: created directory at: artifacts]
[2023-11-14 14:24:37,644: INFO: common: created directory at: artifacts/training]
[2023-11-14 14:37:01,752: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-14 16:19:34,805: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 16:19:34,813: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 16:19:34,824: INFO: common: created directory at: artifacts]
[2023-11-14 16:23:17,356: INFO: common: json file saved at: scores.json]
[2023-11-14 16:23:37,493: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-14 16:23:37,969: INFO: builder_impl: Assets written to: /tmp/tmpqf8m3ozl/model/data/model/assets]
[2023-11-14 16:30:14,741: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 16:30:14,750: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 16:30:14,755: INFO: common: created directory at: artifacts]
[2023-11-14 16:33:40,283: INFO: common: json file saved at: scores.json]
[2023-11-14 16:34:08,961: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-14 16:34:09,438: INFO: builder_impl: Assets written to: /tmp/tmp2elikpez/model/data/model/assets]
[2023-11-14 16:44:59,874: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 16:44:59,885: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 16:44:59,890: INFO: common: created directory at: artifacts]
[2023-11-14 16:48:27,321: INFO: common: json file saved at: scores.json]
[2023-11-14 16:48:35,279: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-14 16:48:35,755: INFO: builder_impl: Assets written to: /tmp/tmprfwjb7z9/model/data/model/assets]
[2023-11-14 17:08:35,431: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 17:08:35,453: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 17:08:35,460: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 17:08:35,464: INFO: common: created directory at: artifacts]
[2023-11-14 17:08:35,468: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-14 17:08:35,470: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 17:08:59,798: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 17:11:50,746: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-14 17:11:50,747: INFO: main: *******************]
[2023-11-14 17:11:50,748: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-14 17:11:50,753: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 17:11:50,852: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 17:11:50,862: INFO: common: created directory at: artifacts]
[2023-11-14 17:11:50,873: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-14 17:11:52,046: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-14 17:11:52,540: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-14 17:11:52,541: INFO: main: *******************]
[2023-11-14 17:11:52,542: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-11-14 17:11:52,548: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 17:11:52,555: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 17:11:52,558: INFO: common: created directory at: artifacts]
[2023-11-14 17:11:52,573: INFO: common: created directory at: artifacts/training]
[2023-11-14 17:23:41,187: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-14 17:23:41,188: INFO: main: *******************]
[2023-11-14 17:23:41,188: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-14 17:23:41,193: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 17:23:41,197: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 17:23:41,200: INFO: common: created directory at: artifacts]
[2023-11-14 17:27:06,487: INFO: common: json file saved at: scores.json]
[2023-11-14 17:27:06,495: INFO: common: json file saved at: scores.json]
[2023-11-14 17:27:06,496: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-11-14 17:44:34,329: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 17:44:34,368: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 17:44:34,370: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 17:44:34,372: INFO: common: created directory at: artifacts]
[2023-11-14 17:44:34,375: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-14 17:44:34,378: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 17:45:08,329: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 17:47:08,179: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-14 17:47:08,180: INFO: main: *******************]
[2023-11-14 17:47:08,180: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-14 17:47:08,183: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 17:47:08,185: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 17:47:08,187: INFO: common: created directory at: artifacts]
[2023-11-14 17:47:08,189: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-14 17:47:08,669: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-14 17:47:09,275: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-14 17:47:09,276: INFO: main: *******************]
[2023-11-14 17:47:09,276: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-11-14 17:47:09,279: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 17:47:09,282: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 17:47:09,284: INFO: common: created directory at: artifacts]
[2023-11-14 17:47:09,294: INFO: common: created directory at: artifacts/training]
[2023-11-14 17:58:41,574: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-14 17:58:41,575: INFO: main: *******************]
[2023-11-14 17:58:41,575: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-14 17:58:41,579: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 17:58:41,583: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 17:58:41,586: INFO: common: created directory at: artifacts]
[2023-11-14 18:02:12,304: INFO: common: json file saved at: scores.json]
[2023-11-14 18:02:12,314: INFO: common: json file saved at: scores.json]
[2023-11-14 18:02:14,301: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-14 18:02:14,666: INFO: builder_impl: Assets written to: /tmp/tmpmwymot35/model/data/model/assets]
[2023-11-14 18:02:32,736: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-11-14 18:04:41,533: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 18:04:41,610: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 18:04:41,612: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 18:04:41,614: INFO: common: created directory at: artifacts]
[2023-11-14 18:04:41,618: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-14 18:04:41,621: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 18:05:09,284: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 18:07:08,014: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-14 18:07:08,014: INFO: main: *******************]
[2023-11-14 18:07:08,015: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-14 18:07:08,018: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 18:07:08,020: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 18:07:08,021: INFO: common: created directory at: artifacts]
[2023-11-14 18:07:08,024: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-14 18:07:08,549: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-14 18:07:09,098: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-14 18:07:09,099: INFO: main: *******************]
[2023-11-14 18:07:09,099: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-11-14 18:07:09,105: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 18:07:09,113: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 18:07:09,117: INFO: common: created directory at: artifacts]
[2023-11-14 18:07:09,121: INFO: common: created directory at: artifacts/training]
[2023-11-14 18:29:58,623: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-14 18:29:58,624: INFO: main: *******************]
[2023-11-14 18:29:58,624: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-14 18:29:58,630: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 18:29:58,635: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 18:29:58,639: INFO: common: created directory at: artifacts]
[2023-11-14 18:33:23,618: INFO: common: json file saved at: scores.json]
[2023-11-14 18:33:23,625: INFO: common: json file saved at: scores.json]
[2023-11-14 18:33:53,686: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/log-batch failed with error code 400 != 200. Response body: '"repo not associated with run"']
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    model_evalution.main()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/components/model_evaluation_mlflow.py", line 62, in log_into_mlflow
    mlflow.log_metrics(
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 677, in log_metrics
    MlflowClient().log_batch(run_id=run_id, metrics=metrics_arr, params=[], tags=[])
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/client.py", line 986, in log_batch
    self._tracking_client.log_batch(run_id, metrics, params, tags)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 394, in log_batch
    self.store.log_batch(run_id=run_id, metrics=metrics_batch, params=[], tags=[])
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 321, in log_batch
    self._call_endpoint(LogBatch, req_body)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/log-batch failed with error code 400 != 200. Response body: '"repo not associated with run"'
[2023-11-14 18:39:34,839: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 18:39:34,847: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 18:39:34,858: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 18:39:34,860: INFO: common: created directory at: artifacts]
[2023-11-14 18:39:34,865: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-14 18:39:34,868: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 18:40:00,327: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 18:41:59,094: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-14 18:41:59,095: INFO: main: *******************]
[2023-11-14 18:41:59,096: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-14 18:41:59,103: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 18:41:59,107: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 18:41:59,110: INFO: common: created directory at: artifacts]
[2023-11-14 18:41:59,116: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-14 18:41:59,555: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-14 18:42:00,231: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-14 18:42:00,233: INFO: main: *******************]
[2023-11-14 18:42:00,233: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-11-14 18:42:00,269: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 18:42:00,276: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 18:42:00,278: INFO: common: created directory at: artifacts]
[2023-11-14 18:42:00,280: INFO: common: created directory at: artifacts/training]
[2023-11-14 19:16:12,419: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-14 19:16:12,421: INFO: main: *******************]
[2023-11-14 19:16:12,421: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-14 19:16:12,424: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 19:16:12,426: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 19:16:12,428: INFO: common: created directory at: artifacts]
[2023-11-14 19:19:37,283: INFO: common: json file saved at: scores.json]
[2023-11-14 19:19:37,292: INFO: common: json file saved at: scores.json]
[2023-11-14 19:19:42,388: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-14 19:19:42,757: INFO: builder_impl: Assets written to: /tmp/tmp4nrmpjdw/model/data/model/assets]
[2023-11-14 19:20:54,592: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-11-14 19:59:43,029: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-14 19:59:43,034: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 19:59:43,036: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 19:59:43,040: INFO: common: created directory at: artifacts]
[2023-11-14 19:59:43,043: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-14 19:59:43,047: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 20:00:12,594: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-14 20:02:13,451: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-14 20:37:31,446: INFO: stage_02_prepare_base_model: *******************]
[2023-11-14 20:37:31,447: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-14 20:37:31,453: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 20:37:31,458: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 20:37:31,462: INFO: common: created directory at: artifacts]
[2023-11-14 20:37:31,466: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-14 20:37:32,470: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-14 20:37:33,150: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-14 20:39:51,851: INFO: stage_03_model_training: *******************]
[2023-11-14 20:39:51,852: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2023-11-14 20:39:51,859: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 20:39:51,867: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 20:39:51,872: INFO: common: created directory at: artifacts]
[2023-11-14 20:39:51,879: INFO: common: created directory at: artifacts/training]
[2023-11-14 20:51:40,174: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-14 20:59:28,161: INFO: stage_04_model_evaluation: *******************]
[2023-11-14 20:59:28,191: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-14 20:59:28,196: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 20:59:28,200: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 20:59:28,205: INFO: common: created directory at: artifacts]
[2023-11-14 21:03:13,082: INFO: common: json file saved at: scores.json]
[2023-11-14 21:03:13,101: INFO: common: json file saved at: scores.json]
[2023-11-14 21:03:24,835: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-14 21:03:25,277: INFO: builder_impl: Assets written to: /tmp/tmp9n5iy3ro/model/data/model/assets]
[2023-11-14 21:03:41,586: ERROR: stage_04_model_evaluation: API request to endpoint /api/2.0/mlflow/runs/get failed with error code 400 != 200. Response body: '"repo not associated with run"']
Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 30, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/components/model_evaluation_mlflow.py", line 72, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tensorflow/__init__.py", line 222, in log_model
    return Model.log(
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/models/model.py", line 552, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 817, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1069, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 448, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 412, in _get_artifact_repo
    run = self.get_run(run_id)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 72, in get_run
    return self.store.get_run(run_id)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 134, in get_run
    response_proto = self._call_endpoint(GetRun, req_body)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/get failed with error code 400 != 200. Response body: '"repo not associated with run"'
[2023-11-14 21:10:02,916: INFO: stage_04_model_evaluation: *******************]
[2023-11-14 21:10:02,919: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-14 21:10:02,925: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 21:10:02,932: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 21:10:02,936: INFO: common: created directory at: artifacts]
[2023-11-14 21:13:29,724: INFO: common: json file saved at: scores.json]
[2023-11-14 21:13:29,733: INFO: common: json file saved at: scores.json]
[2023-11-14 21:13:34,205: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-14 21:13:34,598: INFO: builder_impl: Assets written to: /tmp/tmpzkh02cal/model/data/model/assets]
[2023-11-14 21:14:26,888: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-11-14 21:32:05,826: INFO: stage_02_prepare_base_model: *******************]
[2023-11-14 21:32:05,827: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-14 21:32:05,841: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 21:32:05,845: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 21:32:05,848: INFO: common: created directory at: artifacts]
[2023-11-14 21:32:05,852: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-14 21:32:06,352: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-14 21:32:06,704: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-14 21:36:35,881: INFO: stage_03_model_training: *******************]
[2023-11-14 21:36:35,882: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2023-11-14 21:36:35,889: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 21:36:35,930: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 21:36:35,936: INFO: common: created directory at: artifacts]
[2023-11-14 21:36:35,945: INFO: common: created directory at: artifacts/training]
[2023-11-14 21:48:09,629: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-14 21:53:30,257: INFO: stage_04_model_evaluation: *******************]
[2023-11-14 21:53:30,264: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-14 21:53:30,288: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-14 21:53:30,294: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-14 21:53:30,305: INFO: common: created directory at: artifacts]
[2023-11-14 21:57:12,625: INFO: common: json file saved at: scores.json]
[2023-11-14 21:57:12,636: INFO: common: json file saved at: scores.json]
[2023-11-14 21:57:20,368: ERROR: stage_04_model_evaluation: API request to endpoint /api/2.0/mlflow/runs/log-batch failed with error code 400 != 200. Response body: '"repo not associated with run"']
Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 30, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/components/model_evaluation_mlflow.py", line 62, in log_into_mlflow
    mlflow.log_metrics(
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 677, in log_metrics
    MlflowClient().log_batch(run_id=run_id, metrics=metrics_arr, params=[], tags=[])
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/client.py", line 986, in log_batch
    self._tracking_client.log_batch(run_id, metrics, params, tags)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 394, in log_batch
    self.store.log_batch(run_id=run_id, metrics=metrics_batch, params=[], tags=[])
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 321, in log_batch
    self._call_endpoint(LogBatch, req_body)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/log-batch failed with error code 400 != 200. Response body: '"repo not associated with run"'
[2023-11-15 08:35:30,938: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.26.5.133:8080]
[2023-11-15 08:35:30,940: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-11-15 08:35:48,277: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 08:35:48] "GET / HTTP/1.1" 200 -]
[2023-11-15 08:36:29,621: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/pipeline/prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model/model.h5
[2023-11-15 08:36:29,642: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 08:36:29] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-11-15 08:40:00,384: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 08:40:00] "GET / HTTP/1.1" 200 -]
[2023-11-15 08:40:08,029: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/pipeline/prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model/model.h5
[2023-11-15 08:40:08,038: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 08:40:08] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-11-15 08:42:58,975: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.26.5.133:8080]
[2023-11-15 08:42:58,976: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-11-15 08:43:04,429: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 08:43:04] "GET / HTTP/1.1" 200 -]
[2023-11-15 08:43:13,665: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 08:43:13] "GET / HTTP/1.1" 200 -]
[2023-11-15 08:43:31,185: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/pipeline/prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model/model.h5
[2023-11-15 08:43:31,215: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 08:43:31] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-11-15 08:54:50,021: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.26.5.133:8080]
[2023-11-15 08:54:50,022: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-11-15 08:55:05,780: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 08:55:05] "GET / HTTP/1.1" 200 -]
[2023-11-15 08:55:13,416: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/flask_cors/decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/pipeline/prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/keras/saving/legacy/save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model/model.h5
[2023-11-15 08:55:13,445: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 08:55:13] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2023-11-15 09:00:22,831: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.26.5.133:8080]
[2023-11-15 09:00:22,832: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-11-15 09:00:26,260: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 09:00:26] "GET / HTTP/1.1" 200 -]
[2023-11-15 09:00:35,038: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 09:00:35] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 09:00:59,087: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 09:00:59] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 09:01:10,797: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 09:01:10] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 09:01:21,889: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 09:01:21] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 09:08:00,808: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-15 09:08:00,818: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 09:08:00,828: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 09:08:00,835: INFO: common: created directory at: artifacts]
[2023-11-15 09:08:00,844: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-15 09:08:00,853: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-15 09:08:27,839: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-15 09:09:00,129: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 09:09:00] "GET / HTTP/1.1" 200 -]
[2023-11-15 09:09:09,475: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f521875aaf0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-11-15 09:09:09,478: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 09:09:09] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 09:10:17,193: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-15 09:10:17,194: INFO: main: *******************]
[2023-11-15 09:10:17,194: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-15 09:10:17,200: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 09:10:17,206: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 09:10:17,209: INFO: common: created directory at: artifacts]
[2023-11-15 09:10:17,214: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-15 09:10:19,114: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-15 09:10:19,692: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-15 09:10:19,693: INFO: main: *******************]
[2023-11-15 09:10:19,693: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-11-15 09:10:19,700: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 09:10:19,707: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 09:10:19,711: INFO: common: created directory at: artifacts]
[2023-11-15 09:10:19,719: INFO: common: created directory at: artifacts/training]
[2023-11-15 09:18:52,351: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 09:18:52] "GET / HTTP/1.1" 200 -]
[2023-11-15 09:19:24,164: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-15 09:19:24,190: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 09:19:24,205: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 09:19:24,213: INFO: common: created directory at: artifacts]
[2023-11-15 09:19:24,223: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-15 09:19:24,238: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-15 09:19:53,991: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-15 09:23:37,139: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-15 09:23:37,143: INFO: main: *******************]
[2023-11-15 09:23:37,145: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-15 09:23:37,158: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 09:23:37,175: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 09:23:37,184: INFO: common: created directory at: artifacts]
[2023-11-15 09:23:37,197: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-15 09:23:39,778: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-15 09:23:41,089: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-15 09:23:41,091: INFO: main: *******************]
[2023-11-15 09:23:41,093: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-11-15 09:23:41,107: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 09:23:41,126: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 09:23:41,137: INFO: common: created directory at: artifacts]
[2023-11-15 09:23:41,156: INFO: common: created directory at: artifacts/training]
[2023-11-15 09:32:38,042: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f523f0f8e50> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-11-15 09:32:38,068: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 09:32:38] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 10:21:50,708: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-15 10:21:50,733: INFO: main: *******************]
[2023-11-15 10:21:50,734: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-15 10:21:50,841: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 10:21:50,884: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 10:21:50,901: INFO: common: created directory at: artifacts]
[2023-11-15 10:31:39,224: INFO: common: json file saved at: scores.json]
[2023-11-15 10:31:39,237: INFO: common: json file saved at: scores.json]
[2023-11-15 10:31:52,448: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-15 10:31:53,719: INFO: builder_impl: Assets written to: /tmp/tmp68ue9qkh/model/data/model/assets]
[2023-11-15 10:32:40,314: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-11-15 10:32:42,217: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 10:32:42] "GET /train HTTP/1.1" 200 -]
[2023-11-15 10:37:04,396: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-15 10:37:04,406: INFO: main: *******************]
[2023-11-15 10:37:04,407: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-15 10:37:04,434: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 10:37:04,451: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 10:37:04,461: INFO: common: created directory at: artifacts]
[2023-11-15 10:38:36,996: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 10:38:36] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 10:39:20,469: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 10:39:20] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 10:42:08,293: INFO: common: json file saved at: scores.json]
[2023-11-15 10:42:08,327: INFO: common: json file saved at: scores.json]
[2023-11-15 10:42:29,669: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-15 10:42:30,104: INFO: builder_impl: Assets written to: /tmp/tmpmftpzk8w/model/data/model/assets]
[2023-11-15 10:43:21,680: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-11-15 10:43:22,615: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 10:43:22] "GET /train HTTP/1.1" 200 -]
[2023-11-15 10:43:23,059: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 10:43:23] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2023-11-15 10:46:40,216: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-15 10:46:40,231: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 10:46:40,245: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 10:46:40,254: INFO: common: created directory at: artifacts]
[2023-11-15 10:46:40,267: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-15 10:46:40,280: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-15 10:47:06,658: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-15 10:49:43,180: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-15 10:49:43,182: INFO: main: *******************]
[2023-11-15 10:49:43,183: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-15 10:49:43,193: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 10:49:43,203: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 10:49:43,209: INFO: common: created directory at: artifacts]
[2023-11-15 10:49:43,223: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-15 10:49:44,381: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-15 10:49:45,043: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-15 10:49:45,044: INFO: main: *******************]
[2023-11-15 10:49:45,045: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-11-15 10:49:45,054: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 10:49:45,065: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 10:49:45,071: INFO: common: created directory at: artifacts]
[2023-11-15 10:49:45,082: INFO: common: created directory at: artifacts/training]
[2023-11-15 10:51:09,566: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 10:51:09] "GET / HTTP/1.1" 200 -]
[2023-11-15 11:00:56,909: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 11:00:56] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 11:01:12,356: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 11:01:12] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 11:14:44,934: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-15 11:14:44,935: INFO: main: *******************]
[2023-11-15 11:14:44,935: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-15 11:14:44,943: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 11:14:44,953: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 11:14:44,957: INFO: common: created directory at: artifacts]
[2023-11-15 11:18:35,322: INFO: common: json file saved at: scores.json]
[2023-11-15 11:18:35,331: INFO: common: json file saved at: scores.json]
[2023-11-15 11:18:37,145: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-15 11:18:37,502: INFO: builder_impl: Assets written to: /tmp/tmp8ijzuuyq/model/data/model/assets]
[2023-11-15 11:19:11,967: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-11-15 11:19:12,503: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 11:19:12] "GET /train HTTP/1.1" 200 -]
[2023-11-15 11:20:36,076: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-11-15 11:20:36,086: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 11:20:36,093: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 11:20:36,099: INFO: common: created directory at: artifacts]
[2023-11-15 11:20:36,107: INFO: common: created directory at: artifacts/data_ingestion]
[2023-11-15 11:20:36,115: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-15 11:21:00,220: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/190su2R9ED-uC4x5qgwaqAtSZk1qTEDzh/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2023-11-15 11:23:33,394: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-11-15 11:23:33,395: INFO: main: *******************]
[2023-11-15 11:23:33,396: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-11-15 11:23:33,402: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 11:23:33,409: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 11:23:33,413: INFO: common: created directory at: artifacts]
[2023-11-15 11:23:33,419: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-11-15 11:23:33,852: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-11-15 11:23:34,565: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-11-15 11:23:34,566: INFO: main: *******************]
[2023-11-15 11:23:34,567: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-11-15 11:23:34,575: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 11:23:34,585: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 11:23:34,593: INFO: common: created directory at: artifacts]
[2023-11-15 11:23:34,605: INFO: common: created directory at: artifacts/training]
[2023-11-15 11:34:58,786: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 11:34:58] "GET /train HTTP/1.1" 200 -]
[2023-11-15 11:35:17,739: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.26.5.133:8080]
[2023-11-15 11:35:17,739: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-11-15 11:54:42,060: INFO: stage_04_model_evaluation: *******************]
[2023-11-15 11:54:42,064: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-15 11:54:42,072: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 11:54:42,080: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 11:54:42,086: INFO: common: created directory at: artifacts]
[2023-11-15 11:56:03,314: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 11:56:03] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 11:58:15,347: INFO: common: json file saved at: scores.json]
[2023-11-15 11:58:15,358: INFO: common: json file saved at: scores.json]
[2023-11-15 11:58:21,536: ERROR: stage_04_model_evaluation: API request to endpoint /api/2.0/mlflow/runs/log-batch failed with error code 400 != 200. Response body: '"repo not associated with run"']
Traceback (most recent call last):
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 30, in <module>
    obj.main()
  File "src/cnnClassifier/pipeline/stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "/mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/src/cnnClassifier/components/model_evaluation_mlflow.py", line 61, in log_into_mlflow
    mlflow.log_params(self.config.all_params)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 702, in log_params
    MlflowClient().log_batch(run_id=run_id, metrics=[], params=params_arr, tags=[])
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/client.py", line 986, in log_batch
    self._tracking_client.log_batch(run_id, metrics, params, tags)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 389, in log_batch
    self.store.log_batch(
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 321, in log_batch
    self._call_endpoint(LogBatch, req_body)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/vahid/miniconda3/envs/kidney/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/log-batch failed with error code 400 != 200. Response body: '"repo not associated with run"'
[2023-11-15 11:58:22,370: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 11:58:22] "GET /train HTTP/1.1" 200 -]
[2023-11-15 11:59:35,771: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.26.5.133:8080]
[2023-11-15 11:59:35,772: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-11-15 12:10:11,002: INFO: stage_04_model_evaluation: *******************]
[2023-11-15 12:10:11,005: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-15 12:10:11,015: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 12:10:11,024: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 12:10:11,030: INFO: common: created directory at: artifacts]
[2023-11-15 12:13:47,353: INFO: common: json file saved at: scores.json]
[2023-11-15 12:13:47,380: INFO: common: json file saved at: scores.json]
[2023-11-15 12:14:04,022: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-15 12:14:04,362: INFO: builder_impl: Assets written to: /tmp/tmpizaohzme/model/data/model/assets]
[2023-11-15 12:14:26,823: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-11-15 12:17:19,502: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 12:17:19] "GET /train HTTP/1.1" 200 -]
[2023-11-15 12:26:27,297: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 12:26:27] "GET /train HTTP/1.1" 200 -]
[2023-11-15 13:45:29,785: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 13:45:29] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 13:45:46,179: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 13:45:46] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 13:45:56,689: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 13:45:56] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 15:32:38,771: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 15:32:38] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 15:32:54,490: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fe54c1f9160> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-11-15 15:32:54,493: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 15:32:54] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 15:33:06,577: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fe54c1f9790> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2023-11-15 15:33:06,580: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 15:33:06] "POST /predict HTTP/1.1" 200 -]
[2023-11-15 15:42:30,944: INFO: stage_03_model_training: *******************]
[2023-11-15 15:42:30,945: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2023-11-15 15:42:30,951: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 15:42:30,959: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 15:42:30,963: INFO: common: created directory at: artifacts]
[2023-11-15 15:42:30,971: INFO: common: created directory at: artifacts/training]
[2023-11-15 16:20:25,537: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-15 16:28:56,852: INFO: stage_04_model_evaluation: *******************]
[2023-11-15 16:28:56,855: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-15 16:28:56,868: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-15 16:28:56,881: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-15 16:28:56,891: INFO: common: created directory at: artifacts]
[2023-11-15 16:34:54,115: INFO: common: json file saved at: scores.json]
[2023-11-15 16:34:54,133: INFO: common: json file saved at: scores.json]
[2023-11-15 16:35:02,434: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-15 16:35:03,172: INFO: builder_impl: Assets written to: /tmp/tmpknj_8edl/model/data/model/assets]
[2023-11-15 16:35:42,802: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-11-15 16:37:38,314: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 16:37:38] "GET /train HTTP/1.1" 200 -]
[2023-11-15 17:07:22,501: INFO: _internal: 127.0.0.1 - - [15/Nov/2023 17:07:22] "GET /train HTTP/1.1" 200 -]
[2023-11-16 12:31:53,255: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 12:31:53] "POST /predict HTTP/1.1" 200 -]
[2023-11-16 12:32:07,964: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 12:32:07] "POST /predict HTTP/1.1" 200 -]
[2023-11-16 12:32:36,683: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 12:32:36] "GET / HTTP/1.1" 200 -]
[2023-11-16 12:36:33,800: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 12:36:33] "GET /train HTTP/1.1" 200 -]
[2023-11-16 13:18:07,761: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 13:18:07] "GET / HTTP/1.1" 200 -]
[2023-11-16 13:18:24,811: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 13:18:24] "POST /predict HTTP/1.1" 200 -]
[2023-11-16 13:18:39,331: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 13:18:39] "POST /predict HTTP/1.1" 200 -]
[2023-11-16 13:18:49,064: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 13:18:49] "POST /predict HTTP/1.1" 200 -]
[2023-11-16 13:18:58,462: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 13:18:58] "POST /predict HTTP/1.1" 200 -]
[2023-11-16 13:19:08,747: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 13:19:08] "POST /predict HTTP/1.1" 200 -]
[2023-11-16 13:19:47,094: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 13:19:47] "GET /train HTTP/1.1" 200 -]
[2023-11-16 13:30:54,391: INFO: stage_03_model_training: *******************]
[2023-11-16 13:30:54,393: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2023-11-16 13:30:54,422: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-16 13:30:54,438: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-16 13:30:54,450: INFO: common: created directory at: artifacts]
[2023-11-16 13:30:54,460: INFO: common: created directory at: artifacts/training]
[2023-11-16 14:25:13,416: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-16 14:34:31,692: INFO: stage_04_model_evaluation: *******************]
[2023-11-16 14:34:31,695: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-16 14:34:31,701: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-16 14:34:31,709: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-16 14:34:31,714: INFO: common: created directory at: artifacts]
[2023-11-16 14:41:11,002: INFO: common: json file saved at: scores.json]
[2023-11-16 14:41:11,026: INFO: common: json file saved at: scores.json]
[2023-11-16 14:41:26,579: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-16 14:41:27,231: INFO: builder_impl: Assets written to: /tmp/tmpw0d2gynv/model/data/model/assets]
[2023-11-16 14:42:01,913: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-11-16 14:44:01,896: INFO: _internal: 127.0.0.1 - - [16/Nov/2023 14:44:01] "GET /train HTTP/1.1" 200 -]
[2023-11-20 10:58:55,115: INFO: _internal: 127.0.0.1 - - [20/Nov/2023 10:58:55] "GET / HTTP/1.1" 200 -]
[2023-11-24 09:17:23,063: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.31.152.201:8080]
[2023-11-24 09:17:23,064: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-11-24 09:17:57,105: INFO: _internal: 127.0.0.1 - - [24/Nov/2023 09:17:57] "GET / HTTP/1.1" 200 -]
[2023-11-24 09:18:19,955: INFO: _internal: 127.0.0.1 - - [24/Nov/2023 09:18:19] "POST /predict HTTP/1.1" 200 -]
[2023-11-24 10:39:33,416: INFO: _internal: 127.0.0.1 - - [24/Nov/2023 10:39:33] "POST /predict HTTP/1.1" 200 -]
[2023-11-24 10:43:00,084: INFO: _internal: 127.0.0.1 - - [24/Nov/2023 10:43:00] "GET /train HTTP/1.1" 200 -]
[2023-11-24 10:43:00,482: INFO: _internal: 127.0.0.1 - - [24/Nov/2023 10:43:00] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2023-11-27 12:12:41,702: INFO: _internal: 127.0.0.1 - - [27/Nov/2023 12:12:41] "GET / HTTP/1.1" 200 -]
[2023-11-27 12:50:11,031: INFO: _internal: 127.0.0.1 - - [27/Nov/2023 12:50:11] "POST /predict HTTP/1.1" 200 -]
[2023-11-27 12:50:29,931: INFO: _internal: 127.0.0.1 - - [27/Nov/2023 12:50:29] "POST /predict HTTP/1.1" 200 -]
[2023-11-27 12:59:28,236: INFO: stage_03_model_training: *******************]
[2023-11-27 12:59:28,236: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2023-11-27 12:59:28,241: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-27 12:59:28,250: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-27 12:59:28,256: INFO: common: created directory at: artifacts]
[2023-11-27 12:59:28,260: INFO: common: created directory at: artifacts/training]
[2023-11-27 13:48:38,452: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-11-27 13:52:07,680: INFO: stage_04_model_evaluation: *******************]
[2023-11-27 13:52:07,682: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2023-11-27 13:52:07,686: INFO: common: yaml file: config/config.yaml loaded successfully]
[2023-11-27 13:52:07,691: INFO: common: yaml file: params.yaml loaded successfully]
[2023-11-27 13:52:07,695: INFO: common: created directory at: artifacts]
[2023-11-27 13:55:40,801: INFO: common: json file saved at: scores.json]
[2023-11-27 13:55:40,810: INFO: common: json file saved at: scores.json]
[2023-11-27 13:55:42,555: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2023-11-27 13:55:42,947: INFO: builder_impl: Assets written to: /tmp/tmp5p0niy_7/model/data/model/assets]
[2023-11-27 13:55:46,767: INFO: dir_util: creating /mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/mlruns/0/4764d9f4328540fbbf6a4d39e407e72c/artifacts/model/data]
[2023-11-27 13:55:46,820: INFO: dir_util: creating /mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/mlruns/0/4764d9f4328540fbbf6a4d39e407e72c/artifacts/model/data/model]
[2023-11-27 13:55:46,875: INFO: dir_util: creating /mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/mlruns/0/4764d9f4328540fbbf6a4d39e407e72c/artifacts/model/data/model/assets]
[2023-11-27 13:55:46,893: INFO: dir_util: creating /mnt/c/Users/vahid/Downloads/Kidney-Disease-Classification-MLflow-DVC/mlruns/0/4764d9f4328540fbbf6a4d39e407e72c/artifacts/model/data/model/variables]
[2023-11-27 13:55:47,915: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2023-11-27 13:56:57,712: INFO: _internal: 127.0.0.1 - - [27/Nov/2023 13:56:57] "GET /train HTTP/1.1" 200 -]
[2023-11-30 13:46:59,870: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://172.26.210.118:8080]
[2023-11-30 13:46:59,871: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2023-11-30 13:47:06,918: INFO: _internal: 127.0.0.1 - - [30/Nov/2023 13:47:06] "GET / HTTP/1.1" 200 -]
[2023-11-30 13:54:19,535: INFO: _internal: 127.0.0.1 - - [30/Nov/2023 13:54:19] "GET /train HTTP/1.1" 200 -]
[2023-11-30 13:54:19,920: INFO: _internal: 127.0.0.1 - - [30/Nov/2023 13:54:19] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2023-11-30 14:01:06,916: INFO: _internal: 127.0.0.1 - - [30/Nov/2023 14:01:06] "GET / HTTP/1.1" 200 -]
[2023-11-30 14:01:37,624: INFO: _internal: 127.0.0.1 - - [30/Nov/2023 14:01:37] "POST /predict HTTP/1.1" 200 -]
